### ISSUE TITLE
Add section about frameworks

### ISSUE THREAD

**Issue by blittle** [CanopyTax/frontend-rfc#3]
This should include our loose standardization on React and desire to get off of angular.js. It could also contain specifics about how we are not particular about state management or css frameworks in react.

**Comment by TheMcMurder** [comment]
I assume we'd also need to include the process for adding a new framework to the system. Or at least reference where the process is or "supported" list?

**Comment by blittle** [comment]
@TheMcMurder yeah, I'm thinking: how official is React.js? What is the status of Angular.js at Canopy? We have had experiments with other frameworks (Vue and Svelte) but what is our overall opinion on them? What kind of autonomy vs alignment do we have around frameworks? How far does that go?

**Comment by TheMcMurder** [comment]
#12 is merged so I'm going to close this. I anticipate making more changes to our process as a group. The meeting today was really valuable. 

For context. In the meeting we as a chapter voted to maintain our polyglot approach and eventually add another framework to full support (where React is now)

**Comment by frehner** [comment]
Ah, thanks for documenting the notes of the meeting as well. 👍
