### ISSUE TITLE
Self review on utility and value

### ISSUE THREAD

**Issue by frehner** [CanopyTax/frontend-rfc#8]
I think it will be good if there is a recurring timeline to step back and evaluate whether this process itself is working, helpful, etc. Talk about if we want to continue to do it, and if so, if there are things we can change or improve.

**Comment by internettrans** [comment]
Recurring timeline, meaning a recurring calendar event for the frontend? Or what do you propose for how to regularly evaluate it?

**Comment by frehner** [comment]
Yeah, I was thinking just a recurring calendar event. But I dunno 🤷‍♀️
